const facts = [
    "A shrimp’s heart is located in its head.",
    "The shortest bone in the human body is in your ear, called the stapes.",
    "Penguins can jump up to 6 feet in the air.",
    "A single cloud can weigh over a million pounds.",
    "Sloths can hold their breath longer than dolphins.",
    "The first computer 'bug' was an actual insect stuck in a relay.",
    "A group of owls is called a parliament.",
    "The shortest river in the world is 118 feet long.",
    "Cats have five toes on their front paws but only four on their back paws.",
    "The sun makes up 99.86% of the solar system’s mass.",
    "A blue whale’s tongue weighs as much as an elephant.",
    "Hot water freezes faster than cold water under certain conditions.",
    "The shortest warship in history was a 13-foot-long canoe.",
    "Koalas have fingerprints almost identical to humans.",
    "A day on Mercury lasts 59 Earth days.",
    "The strongest muscle in the human body, relative to size, is the tongue.",
    "Cows have best friends and get stressed when separated.",
    "A group of crows is called a murder.",
    "The shortest warship ever sunk was sunk by a bicycle.",
    "Rainbows can appear at night, caused by moonlight.",
    "A snail can sleep for three years.",
    "The shortest war in space lasted 0 seconds because it never happened.",
    "Dolphins can recognize themselves in mirrors.",
    "The shortest bone in your body is shorter than a grain of rice.",
    "A single teaspoon of neutron star material weighs 6 billion tons.",
    "Bees can recognize human faces.",
    "The deepest part of the ocean is deeper than Mount Everest is tall.",
    "A group of rhinos is called a crash.",
    "Sharks have an acute sense of smell, detecting blood in the water from miles away.",
    "The moon is slowly drifting away from Earth at 3.8 cm per year.",
    "A hummingbird weighs less than a penny.",
    "The first alarm clock could only ring at 4 a.m.",
    "A group of porcupines is called a prickle.",
    "The fastest fish in the ocean can swim 68 miles per hour.",
    "Your stomach acid can dissolve razor blades.",
    "A single strand of spaghetti is called a spaghetto.",
    "The tallest tree in the world is taller than a 37-story building.",
    "Frogs can’t vomit—they eject their entire stomach instead.",
    "A group of jellyfish is called a smack.",
    "The first email was sent in 1971.",
    "A crocodile can’t stick out its tongue.",
    "The quietest room in the world can drive you crazy in 45 minutes.",
    "A group of ferrets is called a business.",
    "The largest desert in the world is Antarctica, not the Sahara.",
    "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
    "The first computer mouse was made of wood.",
    "A group of hippos is called a bloat.",
    "The human body contains enough iron to make a 3-inch nail.",
    "A chameleon’s tongue can be twice its body length.",
    "The coldest temperature ever recorded on Earth was -128.6°F.",
    "A group of kangaroos is called a mob.",
    "The first vending machine dispensed holy water.",
    "A housefly hums in the key of F.",
    "The largest snowflake ever recorded was 15 inches wide.",
    "A group of lemurs is called a conspiracy.",
    "The human brain generates enough electricity to power a small LED.",
    "A shark can grow a new set of teeth in a week.",
    "The first traffic light had only red and green—no yellow.",
    "A group of pandas is called an embarrassment.",
    "The shortest warship ever built was made of concrete.",
    "A cockroach can live for weeks without its head.",
    "The largest volcano in the solar system is on Mars.",
    "A group of ravens is called an unkindness.",
    "The first parachute was tested by jumping off a building with a dog.",
    "A single ant can lift 50 times its own weight.",
    "The shortest war in the air lasted 3 minutes.",
    "A group of squirrels is called a scurry.",
    "The human body has enough carbon to fill 9,000 pencils.",
    "A jellyfish is 95% water.",
    "The first computer game was invented in 1958 and ran on an oscilloscope.",
    "A group of sharks is called a shiver.",
    "The shortest warship ever launched sank on its first voyage.",
    "A dragonfly can fly at speeds up to 36 miles per hour.",
    "The largest animal ever was a prehistoric whale longer than a blue whale.",
    "A group of tigers is called a streak.",
    "The first telephone call was made in 1876.",
    "A human yawn lasts about 6 seconds.",
    "The shortest war in naval history involved a single cannon shot.",
    "A group of zebras is called a dazzle.",
    "The human body has enough fat to make 7 bars of soap.",
    "A pigeon can recognize itself in a mirror.",
    "The first ATM dispensed cash in 1967.",
    "A group of skunks is called a stench.",
    "The shortest warship ever crewed had a crew of one.",
    "A tarantula can survive for two years without food.",
    "The largest hailstone ever recorded weighed 2.25 pounds.",
    "A group of giraffes is called a tower.",
    "The first photograph took 8 hours to expose.",
    "A human sneeze travels at 100 miles per hour.",
    "The shortest war in history involved no casualties.",
    "A group of wolves is called a pack.",
    "The human body contains enough phosphorus to make 2,200 match heads.",
    "A starfish can regrow its arms.",
    "The first TV remote was called 'Lazy Bones.'",
    "A group of bats is called a cauldron.",
    "The shortest warship ever designed was powered by oars.",
    "A praying mantis can turn its head 180 degrees.",
    "The largest iceberg ever recorded was bigger than Jamaica.",
    "A group of deer is called a herd.",
    "The first typewriter had no shift key.",
    "A human hair can hold 3 ounces of weight.",
    "The shortest war in history was won with a single shot.",
    "A group of elk is called a gang.",
    "The human body has enough salt to fill a small shaker.",
    "A sea cucumber can eject its intestines to scare predators.",
    "The first car had a top speed of 10 miles per hour.",
    "A group of moose is called a herd.",
    "The shortest warship ever sunk was sunk by a storm.",
    "A woodpecker can peck 20 times per second.",
    "The largest earthquake ever recorded was a 9.5 magnitude.",
    "A group of hyenas is called a cackle.",
    "The first light bulb lasted 13.5 hours.",
    "A human blink lasts about 0.3 seconds.",
    "The shortest war in history was fought over a flag.",
    "A group of lions is called a pride.",
    "The human body has enough potassium to fire a toy cannon.",
    "A sea urchin can change color to match its surroundings.",
    "The first airplane flight lasted 12 seconds.",
    "A group of bears is called a sleuth.",
    "The shortest warship ever built cost $10 to make.",
    "A grasshopper can jump 20 times its body length.",
    "The largest tornado ever recorded was 2.6 miles wide.",
    "A group of foxes is called a skulk.",
    "The first radio broadcast was in 1906.",
    "A human heartbeat pumps 2,000 gallons of blood a day.",
    "The shortest war in history ended with tea.",
    "A group of goats is called a tribe.",
    "The human body has enough sulfur to kill all fleas on a dog.",
    "A lobster’s brain is in its throat.",
    "The first movie was 2.11 seconds long.",
    "A group of geese on the ground is called a gaggle.",
    "The shortest warship ever floated was made of ice.",
    "A cheetah’s acceleration is faster than a Ferrari’s.",
    "The largest tsunami wave ever recorded was 1,720 feet tall.",
    "A group of swans is called a bevy.",
    "The first refrigerator was invented in 1805.",
    "A human liver can regrow to its full size in weeks.",
    "The shortest war in history started over a pig.",
    "A group of turtles is called a bale.",
    "The human body has enough water to fill a 10-gallon tank.",
    "A crab can regrow its claws.",
    "The first rocket launch into space was in 1942.",
    "A group of vultures is called a committee.",
    "The shortest warship ever used was a raft.",
    "A kangaroo can’t hop backward.",
    "The largest sandcastle ever built was 54 feet tall.",
    "A group of whales is called a pod.",
    "The first electric guitar was made in 1931.",
    "A human eye can distinguish 10 million colors.",
    "The shortest war in history was fought with spears.",
    "A group of ants is called a colony.",
    "The human body has enough calcium to make a small chalk stick.",
    "A seahorse is the slowest fish in the ocean.",
    "The first skyscraper was 10 stories tall.",
    "A group of bees is called a swarm.",
    "The shortest warship ever sunk was sunk by a whale.",
    "A camel can drink 30 gallons of water in 13 minutes.",
    "The largest diamond ever found was 3,106 carats.",
    "A group of eagles is called a convocation.",
    "The first antibiotic was discovered in 1928.",
    "A human lung can float on water.",
    "The shortest war in history lasted one day.",
    "A group of falcons is called a cast.",
    "The human body has enough DNA to stretch to the sun and back.",
    "A squid has a beak like a parrot.",
    "The first submarine was built in 1620.",
    "A group of hawks is called a kettle.",
    "The shortest warship ever crewed sank in 5 minutes.",
    "A giraffe’s neck has the same number of vertebrae as a human’s.",
    "The largest meteorite crater on Earth is 93 miles wide.",
    "A group of peacocks is called a muster.",
    "The first clock was a sundial.",
    "A human jaw can exert 200 pounds of force.",
    "The shortest war in history ended with a handshake.",
    "A group of penguins in water is called a raft.",
    "The human body has enough copper to make a penny.",
    "A walrus can whistle.",
    "The first windmill was built in 644 AD.",
    "A group of platypuses is called a paddle.",
    "The shortest warship ever launched was powered by pedals.",
    "A hedgehog’s heart beats 300 times a minute.",
    "The largest cave in the world can fit a 40-story skyscraper.",
    "A group of salamanders is called a congress.",
    "The first microscope was made in 1590.",
    "A human kidney filters 50 gallons of blood a day.",
    "The shortest war in history was fought over a bridge.",
    "A group of snakes is called a den.",
    "The human body has enough magnesium to spark a small fire.",
    "A sea lion can balance a ball on its nose.",
    "The first hot air balloon flight was in 1783.",
    "A group of sparrows is called a host.",
    "The shortest warship ever built was made of paper.",
    "A polar bear’s fur isn’t white—it’s transparent.",
    "The largest waterfall in the world drops 3,212 feet.",
    "A group of starlings is called a murmuration.",
    "The first compass was invented in China.",
    "A human tear contains a natural painkiller.",
    "The shortest war in history involved a cannon misfire.",
    "A group of toads is called a knot.",
    "The human body has enough zinc to plate a penny.",
    "A barnacle has the longest penis relative to its size in the animal kingdom.",
    "The first steam engine was built in 1698.",
    "A group of weasels is called a sneak.",
    "The shortest warship ever sunk was sunk by a bird.",
    "A reindeer’s eyes change color with the seasons.",
    "The largest canyon in the solar system is on Mars.",
    "A group of wombats is called a wisdom.",
    "The first telescope was patented in 1608.",
    "A human fingernail grows 1 nanometer per second.",
    "The shortest war in history was fought over a cow.",
    "A group of badgers is called a cete.",
    "The human body has enough nickel to make a small coin.",
    "A flamingo can only eat with its head upside down.",
    "The first roller coaster was built in 1884.",
    "A group of clams is called a bed.",
    "The shortest warship ever floated was made of wood scraps.",
    "A porcupine has 30,000 quills.",
    "The largest lake in the world by volume is Lake Baikal.",
    "A group of cobras is called a quiver.",
    "The first battery was invented in 1800.",
    "A human ear has no blood vessels in its cartilage.",
    "The shortest war in history ended with a song.",
    "A group of donkeys is called a pace.",
    "The human body has enough chlorine to disinfect a small pool.",
    "A gecko can regrow its tail.",
    "The first elevator was installed in 1857.",
    "A group of emus is called a mob.",
    "The shortest warship ever launched sank due to a leak.",
    "A sloth’s fur hosts an entire ecosystem of bugs.",
    "The largest flower in the world smells like rotting flesh.",
    "A group of finches is called a charm.",
    "The first sewing machine was invented in 1790.",
    "A human nose can detect rain before it falls.",
    "The shortest war in history was fought over a tree.",
    "A group of gnus is called an implausibility.",
    "The human body has enough arsenic to kill a rat.",
    "A hammerhead shark can sense electric fields.",
    "The first bicycle was invented in 1817.",
    "A group of herrings is called an army.",
    "The shortest warship ever built was powered by a horse.",
    "A meerkat can dig its own body weight in dirt in seconds.",
    "The largest glacier in the world is 270 miles long.",
    "A group of ibises is called a stand.",
    "The first thermometer was invented in 1593.",
    "A human tongue has 2,000 to 8,000 taste buds.",
    "The shortest war in history lasted one hour.",
    "A group of jackals is called a pack.",
    "The human body has enough titanium to make a small bolt.",
    "A narwhal’s tusk is actually a tooth.",
    "The first camera was invented in 1816.",
    "A group of larks is called an exaltation.",
    "The shortest warship ever sunk was sunk by a wave.",
    "A pangolin’s scales are made of keratin, like human nails.",
    "The largest coral reef in the world is over 1,400 miles long.",
    "A group of magpies is called a tiding.",
    "The first zipper was patented in 1893.",
    "A human brain has 86 billion neurons.",
    "The shortest war in history was fought over a boat.",
    "A group of martens is called a richness.",
    "The human body has enough gold to make a tiny speck.",
    "A platypus can glow under UV light.",
    "The first lighthouse was built in 280 BC.",
    "A group of otters is called a romp.",
    "The shortest warship ever floated was made of barrels.",
    "A raccoon can rotate its hind feet 180 degrees.",
    "The largest pyramid in the world is in Mexico, not Egypt.",
    "A group of parrots is called a pandemonium.",
    "The first fountain pen was patented in 1884.",
    "A human tooth can withstand 5,000 pounds of pressure per square inch.",
    "The shortest war in history ended with a letter.",
    "A group of pheasants is called a bouquet.",
    "The human body has enough silver to make a thin wire.",
    "A salmon can jump 6 feet out of water.",
    "The first paper was made in China around 105 AD.",
    "A group of pigeons is called a kit.",
    "The shortest warship ever built was powered by wind.",
    "A tapir’s nose can grab objects like an elephant’s trunk.",
    "The largest bird egg in the world weighs 3 pounds.",
    "A group of quails is called a covey.",
    "The first matches were invented in 1826.",
    "A human spine has 33 vertebrae.",
    "The shortest war in history was fought over a wall.",
    "A group of rabbits is called a fluffle.",
    "The human body has enough tin to coat a small can.",
    "A turkey can run 20 miles per hour.",
    "The first kite was flown 2,800 years ago.",
    "A group of seals is called a harem.",
    "The shortest warship ever sunk was sunk by a rock.",
    "A vulture can smell carrion from a mile away.",
    "The largest pearl ever found weighed 14 pounds.",
    "A group of thrushes is called a mutation.",
    "The first glasses were worn in the 13th century.",
    "A human foot has 26 bones.",
    "The shortest war in history was fought over a road.",
    "A group of trout is called a hover.",
    "The human body has enough lead to make a pencil core.",
    "A wombat’s poop is cube-shaped.",
    "The first fireworks were invented in China 2,000 years ago.",
    "A group of woodpeckers is called a descent.",
    "The shortest warship ever launched was made of reeds."
];

function generateFact() {
    const factElement = document.getElementById('fact');
    const randomIndex = Math.floor(Math.random() * facts.length);
    factElement.style.opacity = '0';
    
    setTimeout(() => {
        factElement.textContent = facts[randomIndex];
        factElement.style.opacity = '1';
    }, 300);
}